### ISSUE TITLE
Support reveresed-Z rendering

### ISSUE THREAD

**Issue by paroj** [OGRECave/ogre#1287]
reference: https://nlguillemot.wordpress.com/2016/12/07/reversed-z-in-opengl/

idea; add `RenderTarget::mIsReversedDepth` flag to
1. select float depth buffer
2. adapt projection matrix

initial implementation for GL3+

**Comment by SNiLD** [comment]
Here's my take on the subject targeted against the 1.11.6 version: https://github.com/SNiLD/ogre/commit/a4d914396255a85535f978759a1f0203bd78fc74

**Comment by SNiLD** [comment]
And here is the 32-bit floating point depth buffer targeted against 1.11.6: https://github.com/SNiLD/ogre/commit/a237399af1562e2cdca27ba53d9cbf413d9de5c3

**Comment by paroj** [comment]
added some minor inline comments to the first commit. The FP depth patch can be cherry-picked as is.

Generally I would rather like to have this as a runtime switch with all conversion being done in the GL3+ render system - similar to `mActiveRenderTarget->requiresTextureFlipping()` is handled.

Can you continue to work on this to eventually provide a PR against master?

**Comment by SNiLD** [comment]
I considered the runtime switch at first as well, but ended up with the compile time option mainly because it requires less work. Runtime switch would need to do all sorts of things throughout Ogre, which is beyond the scope how much I know about Ogre. Also there is no point in flipping between reverse/non-reverse z buffers, you go one way from the start and stick with it so it doesn't make sense to be able to switch it "on the fly". This introduces minimal effort for someone to switch from regular z-buffer to reverse z-buffer because all they need to do is flip the compile time switch and (potentially) fix some shaders.

My hope is that this feature can be incorporated to Ogre so we don't need to keep our separate branch. I will try to migrate from 1.11.6 to master and make a PR against that if I manage to get 1.12 running. However there seems to be many changes again from 1.11 to 1.12 that need to be resolved until I get it working on my end.

**Comment by paroj** [comment]
> there is no point in flipping between reverse/non-reverse z buffers, you go one way from the start and stick with it so it doesn't make sense to be able to switch it

think about supporting pre GL4.5 systems. You should be able to degrade gracefully there. Also some users might want to offer selecting the GL3+ reveresed depth renderer and e.g. the FFP legacy GL one.

> Runtime switch would need to do all sorts of things throughout Ogre

translating `CMPF_LESS_EQUAL > CMPF_GREATER_EQUAL` and doing `clear_d = -0.5*(clear_d-1)` only inside the rendersystem will bring you mostly there

**Comment by SNiLD** [comment]
I added the 32-bit floating point depth buffer as https://github.com/OGRECave/ogre/pull/1290. I try to see if I get reverse z-buffer working with the ideas you've provided.

**Comment by SNiLD** [comment]
Translating `CMPF_LESS_EQUAL -> CMPF_GREATER_EQUAL` done in `void GL3PlusRenderSystem::_setDepthBufferFunction(CompareFunction func)` for example seems problematic if the user specifically wants to use CMPF_LESS_EQUAL. There should be a way to change the "default" behavior (which comes from the default function parameters). Using compile option this is trivial, but how to do this without? The whole API would need an overhaul to overcome the default parameter problem.

**Comment by SNiLD** [comment]
Ok maybe if `GLint GL3PlusRenderSystem::convertCompareFunction(CompareFunction func)` will invert most values passed to it the user can use `CMPF_GREATER_EQUAL` when he wants `CMPF_LESS_EQUAL`...

**Comment by SNiLD** [comment]
There is now a pull request with reverse z-buffer implementation with runtime option on the RenderSystem to enable it. https://github.com/OGRECave/ogre/pull/1291

However the bugs that prevent using higher precision depth buffer prevent this from being as useful as it could be.

**Comment by paroj** [comment]
fixed by #1291

**Comment by SNiLD** [comment]
I fixed the oblique depth projection part incorrectly but we found correct solution to fixing the projection matrix which is included in https://github.com/OGRECave/ogre/pull/1297.
