### ISSUE TITLE
Vulkan RenderSystem

### ISSUE THREAD

**Issue by paroj** [OGRECave/ogre#1690]
# Option: Backport from ogre-next 2.3

> Notes from @darksylinc 

- The `VulkanGlobalBindingTable` emulates the traditional D3D11/GL binding model of binding textures and buffers via a table.
- For simplicity our `VulkanGlobalBindingTable` assumes texture buffers and textures do not interleave (i.e. you can't use slot 0 = texture, slot 1 = buffer, slot 2 = texture); well unless you use an extra binding set (but you only have up to 4 guaranteed).
- `VulkanRootLayout` works with the old low level materials by having prefab root layouts for most common usage (and generators such as RTSS and Hlms can generate root layouts with more fine grained detail)
- `BarrierSolver`. The majority of resources don't need transition tracking.
The ones that do are resources that can be written from the GPU and later read (e.g. RenderTexture -> it's now a texture; UAV read/write -> anything).
- `BarrierSolver` takes care of layout transitions; however the most "problematic" part I see is that in 2.3 the compositor is the perfect place to check for most transitions; while I don't think 1.x has an equivalent.
You would have to squeeze it somewhere and maybe lose some performance gathering/guessing RenderTargets which MAY be used during the current pass and need to be converted to texture.
- Most textures are read only so they don't need barrier solving.
The only exception is when you need to do copy between textures or when uploading data to textures from CPU (i.e. during creation). This is a special case since it doesn't happen often (i.e. for most, it's once during the lifetime of a texture) and we have a special path for these in VulkanQueue::getCopyEncoder / endCopyEncoder (which borrows Metal's idea of grouping copy and blitting operations into an 'encoder')

# Option: V-EZ

Uses higher-level concepts that are very close to the 1.x RenderSystem API. We should at least draw some inspiration from that.

https://github.com/GPUOpen-LibrariesAndSDKs/V-EZ

**Comment by darksylinc** [comment]
I forgot something important:

In Ogre 2.3 we don't use the [Vulkan Memory Allocator](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator), as the VaoManager performs the same functionality (Note: I think V-EZ already uses VMA, not sure).

Nonetheless to deal with some legacy v1 interfaces I wrote the VulkanRawBuffer struct which roughly mimics a MTLBuffer (from Metal) to keep my sanity together.

I don't know if VMA already provides such functionality but if it doesn't, then I recommend writing a small buffer wrapper.

In older APIs a buffer handle (e.g. MTLBuffer, D3D11Resource, GLuint) is all you need. But in Vulkan a buffer is split into 3 parts:

- A VkBuffer handle you use to perform most buffer operations. This is an abstract representation and must be linked to a VkDeviceMemory before it can be used.
- A VkDeviceMemory handle, which is the physical memory backing up the data. Note that on most OSes you can only allocate up to 4096 of these. And a rule of thumb is to have very few of these.
- (Strictly speaking optional, but a necessity) An offset to the suballocation you manage yourself to a region of VkDeviceMemory.

I don't know how much VMA handles this for you. In Ogre these 3 concepts are put into one VulkanRawBuffer (still managed by the VaoManager though).

Also note that mapping GPU memory can only be done once per VkDeviceMemory. So if you want to map e.g. two VkBuffer suballocated to the same VkDeviceMemory, then you probably want to map the whole VkDeviceMemory at once.

In Ogre 2.3 we already had code for this due to our AZDO nature (VulkanDynamicBuffer maps VkDeviceMemory and uses a 'ticket' for handling subregion mapping and unmapping). I think VMA provides the same functionality.

**Comment by paroj** [comment]
fixed in  #1823
