### ISSUE TITLE
c#: operator overloading

### ISSUE THREAD

**Issue by natan-fernandes** [OGRECave/ogre#1918]
It's not really a problem but would be nice to add these functions. I'll be posting here as long as I find it would be cool to implement.

The first one I've stumbled to was `Vector3.Zero`:
I don't really now if it was supposed to be there but I know that FiveM's CitizenFX's Vector3 has this method available and I think it would help to make the code in C# cleaner. Basically `Vector3.Zero` is the same as `new Vector3(0, 0, 0)` .

---

I also think would be nice to have an option to sum/subtract Vector3s which is not currently available, something like this:
```
Vector3 a = new Vector3(10, 10, 10);
Vector3 b = new Vector3(1, 2, 3);
Vector3 sum = a + b;
```
Currently that's how I need to do:
```
Vector3 a = new Vector3(10, 10, 10);
Vector3 b = new Vector3(1, 2, 3);
Vector3 sum = a;
sum.x += b.x;
sum.y += b.y
sum.z += b.z
```
---

There are another ones that were available in Mogre like `Vector3.UNIT_X`, `Vector3.UNIT_Y` and `Vector3.UNIT_Z` which I'm not sure if it's the same as the following code:
```
var unitX = new Vector3(1, 0, 0);
var unitY = new Vector3(0, 1, 0);
var unitZ = new Vector3(0, 0, 1);
```
The same applies for negative values.

I will try to make a PR tonight if you think this worths

**Comment by natan-fernandes** [comment]
`Pair` type is also missing and it's only available in C++ AFAIK. We can use C# tuples instead but I think would be cool to add this as a new type for the C# bindings.
This is how I currently have to do it:
```
var auxT = ray.intersects(mPlane);
Tuple<bool, float> t = new Tuple<bool, float>(auxT.first, auxT.second);
```

**Comment by paroj** [comment]
> I also think would be nice to have an option to sum/subtract Vector3s which is not currently 

there is `Vector3.__add__`, which enables `v1 + v2` in python. If you know how to enable something similar for C#, go for it.
https://github.com/OGRECave/ogre/blob/537b548bfcd329a82407332b7a40118663255589/OgreMain/include/Ogre.i#L127

> There are another ones that were available in Mogre like Vector3.UNIT_X, Vector3.UNIT_Y and Vector3.UNIT_Z which I'm not sure if it's the same as the following code:

these things are equivalent. The reason why `Vector3.UNIT_X` is gone is that `Vector` is now a template with variable length in C++ and static members are a hassle with that. The better alternative would be static functions as `Vector3.zeros()`.

**Comment by natan-fernandes** [comment]
`__add__` is available in Ogre.dll, does it work and should only be renamed to `Add`?

**Comment by paroj** [comment]
I think rather then choosing a better name, you should add real operator overloads in C# with %proxycode as described here:
https://github.com/swig/swig/issues/886

**Comment by akacoding** [comment]
As you already encountered, the Swig wrapper generated by the current interface file contains
`public Vector3 __add__(Vector3 b)` and the other operators.

I would like to add some points about the operator overloading topic and personal observations I have made.

Yes, it is true that these “operators” written as method leads to ugly calculations. But I want to point out why I like this explicit way of writing these “Swig calculations”. Mainly because it is explicit and does not hide the Swig wrapper instances that will be created. Imagine you have an algorithm that will do a lot of calculation in a short time with these operators of `Vector3`.

Every Swig wrapper class that is generated is a `class` i.e. reference type. A short-lived reference type will lead to additional pressure to the Garbage Collection. A way out would be to use a value type that lives on the stack, like a `struct`. But that is not the case for the Swig wrapper classes. I don’t know if Swig supports value type wrapping.

But it is even worse, every Swig wrapper class does have a Finalizer e.g. `~VectorBase3()`. That is generated for security reasons to prevent memory leaks, because most of the time you would not call explicitly `Dispose` on the Swig wrapper types. In that case you add finalizable instances to the Finalizer queue. If the Finalizer runs nothing else will run until it is finished.

Some Swig wrapper classes does own the memory so that you free memory with the `Dispose` call, others do not so that the `Dispose` is a dummy/stub. That is defined by the `bool cMemoryOwn` in wrapper’s constructor. The “operators” of `Vector3` does invoke the constructor with `cMemoryOwn == true`.

Back to my example, if you have a lot of calculation done in a very short time with these objects. You add GC and Finalizer pressure by the sheer number of finalizable Swig wrapper instances.

In our project we had an algorithm with very bad performance because of the reason I just wrote before. We iterate through a lot of triangles, positions and doing calculations with short lived reference types that are finalizable because of Swig. We also saw a very high memory usage that were rising, because of `cMemoryOwn == true` until the all the queued Finalizers were called. Remember that the time the Finalizer is called is nondeterministic. The point about the Finalizers would be fixed if you call Dispose explicitly.

How did we fix our slow calculation? We retrieve the data as it was: A Swig generated `Vector3` but converted it as soon as possible to our own `Vector3` value type to do the calculation on our code base types. That prevents all the intermediate objects. It was a massive improvement. Sure, the first `Vector3` is present for data retrieval from Ogre and must be freed but the only solution for that would be to not use Swig at all, I think.

The problem I have described only applies if you instantiate plenty of objects in a short time. If you have a simple and rare calculation you will not notice any difference.

That is the reason I like `public Vector3 __add__(Vector3 b)` etc. Because it is explicit and you see immediatly that you are dealing with Ogre Swig wrapper types. If you would use an operator overload you would hide these facts.
This is also the reason why I like it that the generated wrapper is not PascalCase like the C# styleguide suggests. It is explicit that you are dealing with Swig wrapper code. That is discussed in https://github.com/OGRECave/ogre/issues/1664.

**Comment by natan-fernandes** [comment]
Well, seems like it's not a good idea to make it follow C# conventions then. I'll be closing this issue in a few days if someone want to say something

**Comment by akacoding** [comment]
By the way, I did not answer the following question:

> `__add__` is available in Ogre.dll, does it work [...]?

Yes `__add__` and the other methods works fine in C#. But as I wrote every return value is a new created `Vector3` Swig wrapper with `cMemoryOwn == true`.

> Well, seems like it's not a good idea to make it follow C# conventions then. I'll be closing this issue in a few days if someone want to say something

I am not saying that you should not do that. It will transform ugly calculations expressed with `__add__`, etc. with operators.
But it will hide that extra information that you are creating intermediate Swig wrapper instances.

For small calculations that are not performance critical it is no problem at all. You will notice no disadvantage.
You can create a PR if you like to have the operator overloads available in C#.

**Comment by akacoding** [comment]
> Are you saying that I need to call `Dispose()` after every single calculation?

No, you do not have to call `Dispose` explicitly. As I wrote, there is a Finalizer like in `~VectorBase3` that will call `Dispose` when executed. All Swig generated wrapper classes do have a Finalizer (noticeable by the ~ prefix). That is for security reasons to prevent memory leaks. Because otherwise you would have to call `Dispose` explicitly on all Swig wrapper objects. That would be a mess.

If you not call `Dispose` explicitly it will be done by the Finalizer.
But if you have a lot of objects with a Finalizer implemented the pressure to the Finalizer Thread increases because of the bigger Finalizer Queue.

If you call `Dispose` explicitly the Finalizer will not be run for that object because of `GC.SuppressFianlize(this)` inside the explicit `Dispose` call.

Nevertheless calling `Dispose` explicitly on every Swig wrapper instance does not solve the problem of much reference type instances lying on the heap (class vs. struct).

As I wrote, we solved that problem by retrieving the data as `Vector3`, converting that data and doing the "big" calculation with our types. That way we minimized the Swig wrapper instances and interaction with Swig.

I recommend you to look into the topics: Garbage Collection, Dispose Pattern and Finalizer. You should also take a look at the generated Swig C# files because you will see how `Dispose`, the Finalizer and the memory ownership is implemented.
