### ISSUE TITLE
API to apply force to a rigid body at a position expressed by its own frame of reference

### ISSUE THREAD

**Issue by addy1997** [OGRECave/ogre#1968]
Hello there,

I am relatively new to the OGRE platform. I am trying to write a plugin to simulate a quadcopter for which I am looking for a suitable API that would allow me to apply force to a position (on the rigid body) relative to its centre of mass. 
Do we have this functionality implemented in OGRE's latest release? Any suggestion is appreciated.

Thanks

**Comment by fletli** [comment]
Hi, Since OGRE is a "pure" rendering engine it does not provide such features out of the box. However, there is a simulation framework Gazebo (http://gazebosim.org/) which uses OGRE as a rendering engine and offers physics simulation API for your purpose. You may also search for existing quadcopter simulations based on ROS and Gazebo.

**Comment by paroj** [comment]
for a more low-level approach there is also: https://github.com/OGRECave/btogre

**Comment by addy1997** [comment]
> for a more low-level approach there is also: https://github.com/OGRECave/btogre

I believe that's obsolete and not in use anymore, is it?
