### ISSUE TITLE
OgreGLSLShaderCommon.cpp the  variable 'mShaderVersion' was change by loaded shader file

### ISSUE THREAD

**Issue by 36yang** [OGRECave/ogre#2116]
#### System Information
- Ogre Version: :grey_question: 1.13.0
- Operating System / Platform: :grey_question:win10
- RenderSystem: :grey_question:gl3+
OgreGLSLShaderCommon.cpp the  variable 'mShaderVersion' was change by loaded shader file
#### Detailled description

 The Problem is in file OgreGLSLShaderCommon.cpp  function of:
    void GLSLShaderCommon::prepareImpl()
the variable 'mShaderVersion' was default 100,   
when  I  have not load a shader befor that  has "#version'  in it。 
then when  load the inner shader  like "ShadowExtrudeDirLight.vert" then
it will   add "#version 100'
then the "transpose()"  will be redefined.

    Can you set the  mShaderVersion by RenderSystem max supported?

**Comment by paroj** [comment]
what you describe is working as intended:
- absence of a "#version" line implies "#version 110": https://www.khronos.org/opengl/wiki/Core_Language_(GLSL)#Version
- however "transpose()" is only available since "#version 120" - therefore we define our own: https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/transpose.xhtml

if you get an redifinition error with "ShadowExtrudeDirLight.vert", this means your driver is doing something wrong. Please provide more info about the used GPU/ driver version.

**Comment by 36yang** [comment]
My Video card is  GeForce GTX 960M, driver version is 436.30。   And  this also happen in  other computers

**Comment by paroj** [comment]
can you proviude a minimal reproduces sample? Loading "ShadowExtrudeDirLight.vert" works fine on nvidia here.

**Comment by paroj** [comment]
no reproducer provided
