### ISSUE TITLE
Ogrecave 1.10 Tested simple example

### ISSUE THREAD

**Issue by kenkit** [OGRECave/ogre#458]
I've searched everywhere but no-one seems to want to help.
Is it that few people are using ogre or is this version specifically targeted towards former 1.9 users. If so I can always downgrade.
I need anyone to test the ogre/samples/bootstrap and confirm if it works. i'll then know my compiled lib has issues. I managed to buld the sample but my version is crushing, no matter what pc I use, or dependanicies I add, I've spent days trying to just build this liblary.
I can't do anything without a simple example.
Please help out.

**Comment by paroj** [comment]
obviously I have tested the Bootstrap sample before checking it in. Also the unit tests work fine on the CI. So there seems to be a problem on your end. In order to get boostrap running, you must build the INSTALL target of Ogre [as described here](https://github.com/OGRECave/ogre/blob/master/BuildingOgre.md) (using CMake). And then build the Bootstrap Sample (again using CMake) [as described here](https://ogrecave.github.io/ogre/api/1.10/setup.html).

You must use CMake - manual configuration in MSVC will not get you there. If it still crashes, I need a trace from the debugger and the contents of your binary dir to investigate further.

Also the dependencies must be build by Ogre and merely copied to the Dependencies dir.

**Comment by kenkit** [comment]
Okay, I figured that all my samples are always crushing, maybe it's a bug with visual studio 2015.
I hope someone else can build ogrecave with visualstudio 2015.
Let me change my configurations.
I appreciate your response.
