### ISSUE TITLE
No warning for '{' in overlay name definition

### ISSUE THREAD

**Issue by marko213** [OGRECave/ogre#696]
This might be a beginner's mistake, but when writing my own application, I came across the following:
When defining an overlay in a .overlay script such as 
```
RandomOverlay {
...
```
no warnings are shown. However, the name of the overlay will, of course, be set to `RandomOverlay {`.

This is mentioned slightly in the [ogre manual](https://ogrecave.github.io/ogre/api/1.10/Overlay-Scripts.html):
> Every overlay in the script must be given a name, which is the line before the first opening ’{’.

Of course, the correct behaviour would be achieved with
```
RandomOverlay
{
...
```
but there is, at parsing time, no indication that anything is wrong.

**Comment by marko213** [comment]
(I messed up the original creation)

This might be a beginner's mistake, but when writing my own application, I came across the following:
When defining a .overlay script such as 
```
RandomOverlay {
...
```
no warnings are shown. However, the name of the overlay will, of course, be set to `RandomOverlay {`.

This is mentioned slightly in the [ogre manual](https://ogrecave.github.io/ogre/api/1.10/Overlay-Scripts.html):
> Every overlay in the script must be given a name, which is the line before the first opening ’{’.

Of course, the correct behaviour would be achieved with
```
RandomOverlay
{
...
```
but there is, at parsing time, no indication that anything is wrong.

**Comment by paroj** [comment]
this is due to Overlay still using a custom script parser:
https://github.com/OGRECave/ogre/blob/v1.10.11/Components/Overlay/src/OgreOverlayManager.cpp#L197

instead of the new Script parser introduced in Ogre 1.6:
https://github.com/OGRECave/ogre/blob/v1.10.11/OgreMain/src/OgreMaterialManager.cpp#L148-L151

however the new parser requires type keywords (e.g. overlay in front of the name). Therefore existing scripts would need changes.

**Comment by paroj** [comment]
feel free to create a PR adding a warning to the existing code though
