### ISSUE TITLE
TextureUnitState::ensurePrepared/ensureLoaded bug

### ISSUE THREAD

**Issue by arkeon7** [OGRECave/ogre#729]
#### System Information
- Ogre Version:: Master
- Operating System / Platform:  windows
- RenderSystem:  OpenGL

#### Detailled description
TextureUnitState::ensurePrepared set back to the texture ptr the formats and mTextureSrcMipmaps.
But mTextureSrcMipmaps is int and can be -1 since void setNumMipmaps(uint32 num) is unsigned int.
This result as a very big number in mipmaps and crash.

In my case the problem is shown when I use manual textures and apply it after on the material texture unit. Also my original texture ptr is overwritten by the unset texture unit members.
        tex->setTextureType(mTextureType);
        tex->setFormat(mDesiredFormat);
        tex->setGamma(mGamma);
        tex->setNumMipmaps(mTextureSrcMipmaps);
        tex->setHardwareGammaEnabled(mHwGamma);
        tex->setTreatLuminanceAsAlpha(mIsAlpha);

**Comment by paroj** [comment]
> But mTextureSrcMipmaps is int and can be -1 since void setNumMipmaps(uint32 num) is unsigned int.

thanks! nice catch.

> Also my original texture ptr is overwritten by the unset texture unit members.

this one is more difficult, as the state is duplicated between TUS and Texture and the precedence changed due to the recent refactoring. The best for now is to cal tex->load() manually - then anything in TUS will have no effect.
In the longer term we should remove the duplication.
