### ISSUE TITLE
Assertion fails on resizing render window on macOS

### ISSUE THREAD

**Issue by botteroa-si** [OGRECave/ogre#790]
#### System Information
- Ogre Version:  1.10 
- Operating System / Platform: macOS
- RenderSystem: OpenGL

#### Detailled description
The situation is as follows: we have a Qt application that offers the possibility to have multiple Ogre render windows embedded in the Qt main window. As long as the number of embedded ogre windows is equal to 1, everything works fine. When the number of embedded widows becomes bigger than one, then the following assertion fails, when one tries to resize the Qt window (the assert is in `OgreOSXCocoaWindow.mm, line 410`):
```
Assertion failed: (mView == nil || int(mHeight) == _getPixelFromPoint([mView frame].size.height)), function getHeight
```
A very similar behaviour was already reported some years ago in [this post](https://forums.ogre3d.org/viewtopic.php?t=93562) on the Ogre Forums, but it seems to have been ignored. In our case, though, if the assertion is commented out, there is no crash after the window has been successfully resized, and everything continues to work as expected.

As to be expected (given that location of the assert), this problem doesn't appear on Linux or Windows, where everything works fine.

**Comment by paroj** [comment]
does calling `RenderWindow::windowMovedOrResized` help?

**Comment by fbridault** [comment]
Hi, in fw4spl-ogre fork, we simply removed the assert https://github.com/fw4spl-org/ogre/commit/d249ff6155287ab4352f4f8e412113e55a8593a4. I spent a while to understand the execution flow but for me, it turned out that the size of the window might be out-of-sync because the rendering event is triggered before the resize event.  We live fine with that fix for few months... But maybe there is a cleaner fix ?

**Comment by paroj** [comment]
unfortunately I do not know enough about OSX. @eugenegff

**Comment by paroj** [comment]
the solution should be to call `RenderWindow::windowMovedOrResized` each time you resize the parent Qt Window.

**Comment by eugenegff** [comment]
You should call RenderWindow::windowMovedOrResized, as Pavel suggested. You can of course hide error rather than fix it, by commenting assertion out. Quite possible that windowMovedOrResized would be occasionally called soon, and user would not see the problem. Ogre surely saw the problem, and report it via assertion

**Comment by botteroa-si** [comment]
@paroj, @fbridault, @eugenegff, thank you very much for your answers and comments! 

It turned out that, indeed, `RenderWindow::windowMovedOrResized` was called, but in the wrong place. Calling it from the direct Qt parent fixed the problem.
